# Generated by Django 3.2.20 on 2024-05-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена товара'),
            preserve_default=False,
        ),
    ]
