# Generated by Django 3.2.20 on 2024-05-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_productsinorder_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinorder',
            name='total_price',
        ),
    ]
