# Generated by Django 3.2.20 on 2024-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_productsinorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinorder',
            name='total_price',
            field=models.IntegerField(default=1, verbose_name='Итоговая цена в заказе'),
            preserve_default=False,
        ),
    ]
