# Generated by Django 3.2.20 on 2024-05-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_productsinorder_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinorder',
            name='total_price',
            field=models.TextField(verbose_name='Итоговая цена в заказе'),
        ),
    ]
