# Generated by Django 3.2.20 on 2024-05-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_productsinorder_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinorder',
            name='total_price',
        ),
    ]
