# Generated by Django 3.2.20 on 2024-05-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_productsinorder_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField(verbose_name='Дата выполнения')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Выполнение услуги',
                'verbose_name_plural': 'Выполнения услуг',
            },
        ),
    ]
