# Generated by Django 3.2.20 on 2024-05-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_serviceexecution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceexecution',
            options={'verbose_name': 'Выполнение услуги', 'verbose_name_plural': 'Выполнениe услуг'},
        ),
        migrations.AddField(
            model_name='serviceexecution',
            name='employee',
            field=models.CharField(default=1, max_length=255, verbose_name='Сотрудник'),
            preserve_default=False,
        ),
    ]
