# Generated by Django 3.2.20 on 2024-05-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_productsinorder_all_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinorder',
            name='all_total_price',
        ),
    ]
