# Generated by Django 3.2.20 on 2024-05-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_remove_productsinorder_all_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая итоговая цена'),
        ),
    ]
